### ISSUE TITLE
Crash when opening inventory in 24w40a

### ISSUE THREAD

**Issue by MerpisMe** [O7410/Bundles-Beyond#1]
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_9929 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_465.method_25426(class_465.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_10260.method_25426(class_10260.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25426(class_490.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1203) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2003) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1868) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1313) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:934) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.5.jar:?]
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method changeScrollBehavior(ILorg/joml/Vector2i;III)I in bundles-beyond.mixins.json:BundleTooltipSubmenuHandlerMixin from mod bundles-beyond failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap client-bundles-beyond-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at com.llamalad7.mixinextras.wrapper.InjectorWrapperImpl.doPostInject(InjectorWrapperImpl.java:83) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.doPostInject(SugarWrapperImpl.java:88) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.postInject(WrapperInjectionInfo.java:84) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.5.jar:?]
	... 17 more
	Suppressed: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Failed to validate sugar @Local(name = "i") int on method changeScrollBehavior(I)I from mixin bundles-beyond.mixins.json:BundleTooltipSubmenuHandlerMixin from mod bundles-beyond in target method net/minecraft/class_9929::method_61973(DDILnet/minecraft/class_1799;)Z at instruction InjectionNode[MethodInsn [INVOKESTATIC] net/minecraft/class_9928::method_61972(DII)I]
		at com.llamalad7.mixinextras.sugar.impl.SugarInjector.validateApplicators(SugarInjector.java:183) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
		at com.llamalad7.mixinextras.sugar.impl.SugarInjector.prepareSugar(SugarInjector.java:161) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
		at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.prepare(SugarWrapperImpl.java:71) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
		at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.prepare(WrapperInjectionInfo.java:63) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.5.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.5.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.5.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
		at net.minecraft.class_465.method_25426(class_465.java:106) ~[client-intermediary.jar:?]
		at net.minecraft.class_10260.method_25426(class_10260.java:26) ~[client-intermediary.jar:?]
		at net.minecraft.class_490.method_25426(class_490.java:50) ~[client-intermediary.jar:?]
		at net.minecraft.class_437.method_25423(class_437.java:309) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1507(class_310.java:1203) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1508(class_310.java:2003) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1574(class_310.java:1868) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1523(class_310.java:1313) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1514(class_310.java:934) [client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
	Caused by: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Unable to find matching local!
		at com.llamalad7.mixinextras.sugar.impl.LocalSugarApplicator.validate(LocalSugarApplicator.java:48) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
		at com.llamalad7.mixinextras.sugar.impl.SugarInjector.validateApplicators(SugarInjector.java:179) ~[mixinextras-0.4.1-215bdc40eef77b8f.jar:?]
		... 30 more

**Comment by O7410** [comment]
Thank you!
If not for you, i would've not known there was an issue (it worked in the development environment)
I got like 50 downloads for the broken version 😭 
I uploaded a new version that should work
again, thank you for reporting this

**Comment by MerpisMe** [comment]
> Thank you! If not for you, i would've not known there was an issue (it worked in the development environment) I got like 50 downloads for the broken version 😭 I uploaded a new version that should work again, thank you for reporting this

lol, no problem, i totally get the struggle so no worries!! glad to hear it's fixed though!
